// Simulated Demo Data for HimaGuard (SIH26192)
// NOTE: All metrics, readings, and predictions are simulated for demonstration purposes.

export const MOCK_ROLES = [
  {
    id: 'disaster_authority',
    name: 'Disaster Authority (SDMA / NDRF)',
    description: 'Strategic commander with full broadcast, alert creation, and evacuation authorization privileges',
    badge: 'State Commander',
    defaultEmail: 'commander.sdma@uk.gov.in'
  },
  {
    id: 'emergency_operator',
    name: 'DEOC Emergency Operator',
    description: 'District Emergency Operations Center desk officer monitoring real-time sensor telemetry',
    badge: 'Chamoli DEOC',
    defaultEmail: 'operator.chamoli@deoc.in'
  },
  {
    id: 'system_admin',
    name: 'Systems Administrator',
    description: 'Technical telemetry supervisor managing IoT gateways, ML models, and health checks',
    badge: 'System Admin',
    defaultEmail: 'sysadmin@himaguard.in'
  }
];

export const INITIAL_VILLAGES = [
  {
    id: 'v-dharali',
    name: 'Dharali',
    district: 'Uttarkashi',
    riverBasin: 'Bhagirathi',
    elevation: 2680,
    population: 1250,
    lat: 31.0336,
    lng: 78.7845,
    riskLevel: 'low',
    floodProbability: 14,
    leadTime: '> 6 hours',
    rainfall1h: 18.5,
    soilMoisture: 56.2,
    waterLevel: 1.25,
    waterLevelTrend: 'stable',
    dischargeRate: 45,
    slopeAngle: 34,
    vulnerableWards: ['Ward 1 - Riverside Bazaar', 'Ward 3 - Kheer Ganga Confluence'],
    sensors: ['AWS-UK-01', 'SOIL-UK-01', 'RADAR-UK-01'],
    shelters: ['sh-dharali-gmvn', 'sh-dharali-school'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'normal', detail: '18.5 mm/h (Below FFG threshold of 45 mm/h)' },
      { factor: 'Topsoil Saturation (TDR)', status: 'normal', detail: '56.2% saturation - Subsurface drainage active' },
      { factor: 'Bhagirathi Gauge Level', status: 'normal', detail: '1.25 m (Safe buffer: 1.85 m below warning mark)' },
      { factor: 'Catchment Slope Hazard', status: 'warning', detail: '34 deg incline creates rapid funneling if cloudburst occurs' },
      { factor: 'Upstream Glacial Splay', status: 'normal', detail: 'Glacial lake levels at stable equilibrium' }
    ]
  },
  {
    id: 'v-joshimath',
    name: 'Joshimath',
    district: 'Chamoli',
    riverBasin: 'Alaknanda / Dhauliganga',
    elevation: 1890,
    population: 16700,
    lat: 30.5564,
    lng: 79.5662,
    riskLevel: 'high',
    floodProbability: 73,
    leadTime: '2 hrs 15 mins',
    rainfall1h: 68.2,
    soilMoisture: 84.5,
    waterLevel: 2.85,
    waterLevelTrend: 'rising',
    dischargeRate: 280,
    slopeAngle: 38,
    vulnerableWards: ['Sunil Ward', 'Manohar Bagh', 'Singh Dhar Lower'],
    sensors: ['AWS-CH-01', 'SOIL-CH-01', 'RADAR-CH-01', 'SEISMIC-CH-01'],
    shelters: ['sh-joshimath-inter'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'hazard', detail: '68.2 mm/h heavy cloud concentration exceeding flash threshold' },
      { factor: 'Topsoil Saturation (TDR)', status: 'hazard', detail: '84.5% saturation - Severe pore-water pressure detected' },
      { factor: 'Alaknanda Gauge Level', status: 'warning', detail: '2.85 m (+0.45 m in last 45 minutes)' },
      { factor: 'Slope & Subsidence History', status: 'hazard', detail: 'Known active subsidence zone with 38 deg scarp slope' },
      { factor: 'Upstream Debris Surges', status: 'warning', detail: 'Rishi Ganga tributary reporting debris accumulation' }
    ]
  },
  {
    id: 'v-kedarnath',
    name: 'Kedarnath Valley',
    district: 'Rudraprayag',
    riverBasin: 'Mandakini',
    elevation: 3584,
    population: 1800,
    lat: 30.7352,
    lng: 79.0669,
    riskLevel: 'moderate',
    floodProbability: 48,
    leadTime: '3 hrs 40 mins',
    rainfall1h: 42.0,
    soilMoisture: 71.0,
    waterLevel: 1.85,
    waterLevelTrend: 'rising',
    dischargeRate: 110,
    slopeAngle: 42,
    vulnerableWards: ['Temple Environs', 'Rambara Path Lower'],
    sensors: ['AWS-RP-01', 'RADAR-RP-01'],
    shelters: ['sh-dharali-gmvn'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'warning', detail: '42.0 mm/h steady alpine rain' },
      { factor: 'Topsoil Saturation (TDR)', status: 'warning', detail: '71.0% saturation in moraine sediment' },
      { factor: 'Mandakini Headwaters', status: 'warning', detail: '1.85 m (+0.3m/h gradient)' },
      { factor: 'Moraine Dam Watch', status: 'normal', detail: 'Chorabari moraine basin free of sudden blockages' },
      { factor: 'Valley Confinement', status: 'hazard', detail: 'Steep glacial canyon accelerates wave speed' }
    ]
  },
  {
    id: 'v-chamoli',
    name: 'Chamoli Gopeshwar',
    district: 'Chamoli',
    riverBasin: 'Alaknanda',
    elevation: 1550,
    population: 21400,
    lat: 30.4132,
    lng: 79.3245,
    riskLevel: 'moderate',
    floodProbability: 38,
    leadTime: '4 hrs 20 mins',
    rainfall1h: 36.4,
    soilMoisture: 67.8,
    waterLevel: 1.70,
    waterLevelTrend: 'rising',
    dischargeRate: 145,
    slopeAngle: 28,
    vulnerableWards: ['Koteshwar Ghat Area', 'Lower Bazar Road'],
    sensors: ['AWS-CH-02', 'RADAR-CH-02'],
    shelters: ['sh-joshimath-inter'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'warning', detail: '36.4 mm/h steady rain' },
      { factor: 'Topsoil Saturation (TDR)', status: 'normal', detail: '67.8% saturation - adequate retention buffer' },
      { factor: 'Alaknanda Level', status: 'normal', detail: '1.70 m - Below warning threshold (2.50 m)' },
      { factor: 'Urban Storm Drainage', status: 'normal', detail: 'Main stormwater bypass operational' },
      { factor: 'Tributary Backflow Risk', status: 'normal', detail: 'Balkhila river confluence flowing smoothly' }
    ]
  },
  {
    id: 'v-badrinath',
    name: 'Badrinath Puri',
    district: 'Chamoli',
    riverBasin: 'Alaknanda',
    elevation: 3133,
    population: 2400,
    lat: 30.7433,
    lng: 79.4938,
    riskLevel: 'low',
    floodProbability: 18,
    leadTime: '> 6 hours',
    rainfall1h: 15.2,
    soilMoisture: 52.0,
    waterLevel: 1.10,
    waterLevelTrend: 'stable',
    dischargeRate: 35,
    slopeAngle: 31,
    vulnerableWards: ['Alaknanda Embankment', 'Devdarshini'],
    sensors: ['AWS-CH-03', 'RADAR-CH-03'],
    shelters: ['sh-joshimath-inter'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'normal', detail: '15.2 mm/h light alpine precipitation' },
      { factor: 'Topsoil Saturation (TDR)', status: 'normal', detail: '52.0% saturation' },
      { factor: 'Alaknanda Headwater', status: 'normal', detail: '1.10 m (Normal summer runoff)' },
      { factor: 'Nar-Narayan Slopes', status: 'normal', detail: 'No rockfall or debris dams observed' },
      { factor: 'Channel Capacity', status: 'normal', detail: 'Wide reinforced riverbed absorbs surges' }
    ]
  },
  {
    id: 'v-rudraprayag',
    name: 'Rudraprayag Sangam',
    district: 'Rudraprayag',
    riverBasin: 'Alaknanda & Mandakini Confluence',
    elevation: 895,
    population: 9300,
    lat: 30.2844,
    lng: 78.9811,
    riskLevel: 'high',
    floodProbability: 71,
    leadTime: '2 hrs 40 mins',
    rainfall1h: 62.0,
    soilMoisture: 81.3,
    waterLevel: 3.10,
    waterLevelTrend: 'rising',
    dischargeRate: 340,
    slopeAngle: 32,
    vulnerableWards: ['Sangam Confluence Ghat', 'Main Bazaar Lower'],
    sensors: ['AWS-RP-02', 'RADAR-RP-02', 'SOIL-RP-01'],
    shelters: ['sh-rudraprayag-pg'],
    whyFactors: [
      { factor: 'Dual-Basin Inflow Surge', status: 'hazard', detail: 'Both Mandakini and Alaknanda cresting simultaneously' },
      { factor: '1h Precipitation Rate', status: 'hazard', detail: '62.0 mm/h over upstream gorges' },
      { factor: 'Confluence Water Level', status: 'hazard', detail: '3.10 m (Only 0.4m below flood danger mark)' },
      { factor: 'Topsoil Saturation (TDR)', status: 'hazard', detail: '81.3% saturated river canyon banks' },
      { factor: 'Hydraulic Backwater Effect', status: 'warning', detail: 'Narrow gorge constricts discharge at confluence point' }
    ]
  },
  {
    id: 'v-uttarkashi',
    name: 'Uttarkashi',
    district: 'Uttarkashi',
    riverBasin: 'Bhagirathi',
    elevation: 1158,
    population: 17500,
    lat: 30.7268,
    lng: 78.4354,
    riskLevel: 'moderate',
    floodProbability: 41,
    leadTime: '4 hrs 10 mins',
    rainfall1h: 38.0,
    soilMoisture: 69.4,
    waterLevel: 1.95,
    waterLevelTrend: 'rising',
    dischargeRate: 160,
    slopeAngle: 26,
    vulnerableWards: ['Gyan Ganga Confluence', 'Tiloth Powerhouse Sector'],
    sensors: ['AWS-UK-02', 'RADAR-UK-02'],
    shelters: ['sh-dharali-gmvn'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'warning', detail: '38.0 mm/h steady monsoon rain' },
      { factor: 'Topsoil Saturation (TDR)', status: 'normal', detail: '69.4% saturation' },
      { factor: 'Bhagirathi Level', status: 'normal', detail: '1.95 m - within engineered levee tolerances' },
      { factor: 'Upstream Dam Regulation', status: 'normal', detail: 'Maneri Dam spillway gates throttled safely' },
      { factor: 'Landslide Dam Check', status: 'normal', detail: 'Tambakhani ridge monitored; no blockages' }
    ]
  },
  {
    id: 'v-srinagar',
    name: 'Srinagar Garhwal',
    district: 'Pauri Garhwal',
    riverBasin: 'Alaknanda',
    elevation: 560,
    population: 37900,
    lat: 30.2223,
    lng: 78.7844,
    riskLevel: 'low',
    floodProbability: 22,
    leadTime: '> 6 hours',
    rainfall1h: 21.0,
    soilMoisture: 58.0,
    waterLevel: 1.40,
    waterLevelTrend: 'stable',
    dischargeRate: 95,
    slopeAngle: 18,
    vulnerableWards: ['ITI Plains', 'SSB Campus Perimeter'],
    sensors: ['AWS-PA-01', 'RADAR-PA-01'],
    shelters: ['sh-rudraprayag-pg'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'normal', detail: '21.0 mm/h moderate shower' },
      { factor: 'Topsoil Saturation (TDR)', status: 'normal', detail: '58.0% saturation' },
      { factor: 'Alaknanda Hydro Buffer', status: 'normal', detail: 'Srinagar Hydroelectric Dam buffer basin available' },
      { factor: 'Riverbed Topography', status: 'normal', detail: 'Broad braided channel disperses peak waves' },
      { factor: 'Early Warning Window', status: 'normal', detail: 'Sufficient 6+ hr buffer from upper Chamoli surge' }
    ]
  },
  {
    id: 'v-karnaprayag',
    name: 'Karnaprayag',
    district: 'Chamoli',
    riverBasin: 'Alaknanda & Pindar Confluence',
    elevation: 860,
    population: 8200,
    lat: 30.2589,
    lng: 79.2181,
    riskLevel: 'moderate',
    floodProbability: 44,
    leadTime: '3 hrs 50 mins',
    rainfall1h: 40.5,
    soilMoisture: 72.5,
    waterLevel: 2.10,
    waterLevelTrend: 'rising',
    dischargeRate: 175,
    slopeAngle: 30,
    vulnerableWards: ['Subhash Nagar Lower', 'Sangam Market'],
    sensors: ['AWS-CH-04', 'RADAR-CH-04'],
    shelters: ['sh-joshimath-inter'],
    whyFactors: [
      { factor: 'Pindar River Discharge', status: 'warning', detail: 'Glacial runoff and rain elevating Pindar discharge' },
      { factor: '1h Precipitation Rate', status: 'warning', detail: '40.5 mm/h rain over Tharali basin' },
      { factor: 'Alaknanda Water Level', status: 'warning', detail: '2.10 m (Elevating steadily at +0.25 m/hr)' },
      { factor: 'Topsoil Saturation (TDR)', status: 'warning', detail: '72.5% saturation along river cuts' },
      { factor: 'Gorge Bottleneck', status: 'warning', detail: 'Subhash Nagar highway revetment under hydrodynamic pressure' }
    ]
  },
  {
    id: 'v-mana',
    name: 'Mana Village',
    district: 'Chamoli',
    riverBasin: 'Saraswati / Alaknanda',
    elevation: 3200,
    population: 1210,
    lat: 30.7712,
    lng: 79.4975,
    riskLevel: 'low',
    floodProbability: 11,
    leadTime: '> 6 hours',
    rainfall1h: 12.0,
    soilMoisture: 48.0,
    waterLevel: 0.95,
    waterLevelTrend: 'stable',
    dischargeRate: 28,
    slopeAngle: 36,
    vulnerableWards: ['Bhim Pul Gorge Approach'],
    sensors: ['AWS-CH-05'],
    shelters: ['sh-joshimath-inter'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'normal', detail: '12.0 mm/h light drizzle' },
      { factor: 'Topsoil Saturation (TDR)', status: 'normal', detail: '48.0% rocky glacial till' },
      { factor: 'Saraswati Natural Canyon', status: 'normal', detail: 'Deep bedrock gorge prevents surface flooding' },
      { factor: 'Upper Catchment Snowpack', status: 'normal', detail: 'Freezing level high; stable snowpack' },
      { factor: 'ITBP High-Altitude Watch', status: 'normal', detail: 'Visual aerial observation clear' }
    ]
  },
  {
    id: 'v-tilwara',
    name: 'Tilwara',
    district: 'Rudraprayag',
    riverBasin: 'Mandakini',
    elevation: 1020,
    population: 3100,
    lat: 30.3478,
    lng: 78.9744,
    riskLevel: 'high',
    floodProbability: 66,
    leadTime: '2 hrs 55 mins',
    rainfall1h: 58.0,
    soilMoisture: 79.0,
    waterLevel: 2.70,
    waterLevelTrend: 'rising',
    dischargeRate: 240,
    slopeAngle: 29,
    vulnerableWards: ['Sumerpur Embankment', 'Tilwara Bridge Flat'],
    sensors: ['AWS-RP-03', 'RADAR-RP-03'],
    shelters: ['sh-rudraprayag-pg'],
    whyFactors: [
      { factor: 'Mandakini Surge Transmission', status: 'hazard', detail: 'Rapid flood wave traveling from upper Kedarnath gorges' },
      { factor: '1h Precipitation Rate', status: 'hazard', detail: '58.0 mm/h localized squall line' },
      { factor: 'Channel Level', status: 'warning', detail: '2.70 m (0.8 m beneath critical overflow)' },
      { factor: 'Soil Saturation (TDR)', status: 'hazard', detail: '79.0% saturation with localized slope slippage' },
      { factor: 'Low-Lying Bridge Flat', status: 'hazard', detail: 'Shallow floodplain susceptible to backwater pool' }
    ]
  },
  {
    id: 'v-govindghat',
    name: 'Govindghat',
    district: 'Chamoli',
    riverBasin: 'Hemganga & Alaknanda',
    elevation: 1828,
    population: 2150,
    lat: 30.6225,
    lng: 79.5606,
    riskLevel: 'critical',
    floodProbability: 92,
    leadTime: '45 mins',
    rainfall1h: 88.0,
    soilMoisture: 92.5,
    waterLevel: 3.35,
    waterLevelTrend: 'rising',
    dischargeRate: 395,
    slopeAngle: 41,
    vulnerableWards: ['Gurudwara Lower Complex', 'Suspension Bridge Pylon Area', 'Taxi Stand Embankment'],
    sensors: ['AWS-CH-06', 'RADAR-CH-06', 'SOIL-CH-02'],
    shelters: ['sh-govindghat-gurudwara-upper'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'hazard', detail: '88.0 mm/h intense cloudburst cell over Bhyundar Valley' },
      { factor: 'Topsoil Saturation (TDR)', status: 'hazard', detail: '92.5% saturation - Total infiltration excess' },
      { factor: 'Hemganga River Surge', status: 'hazard', detail: '3.35 m (0.15 m above Danger Mark; rapid rise)' },
      { factor: 'Catchment Slope & Debris Flow', status: 'hazard', detail: '41 deg angle carrying massive boulders and slurry downstream' },
      { factor: 'Infrastructure Vulnerability', status: 'hazard', detail: 'Gurudwara parking and footbridge apron in immediate inundation zone' }
    ]
  },
  {
    id: 'v-guptkashi',
    name: 'Guptkashi',
    district: 'Rudraprayag',
    riverBasin: 'Mandakini Valley Ridge',
    elevation: 1319,
    population: 5400,
    lat: 30.5228,
    lng: 79.0772,
    riskLevel: 'low',
    floodProbability: 19,
    leadTime: '> 6 hours',
    rainfall1h: 24.0,
    soilMoisture: 54.0,
    waterLevel: 1.15,
    waterLevelTrend: 'stable',
    dischargeRate: 40,
    slopeAngle: 25,
    vulnerableWards: ['Nala Village Slope'],
    sensors: ['AWS-RP-04'],
    shelters: ['sh-rudraprayag-pg'],
    whyFactors: [
      { factor: 'Ridge Topography', status: 'normal', detail: 'Located 300m above river valley bed - no inundation risk' },
      { factor: '1h Precipitation Rate', status: 'normal', detail: '24.0 mm/h standard mountain rainfall' },
      { factor: 'Topsoil Saturation (TDR)', status: 'normal', detail: '54.0% saturation' },
      { factor: 'Landslide Hazard On Access Road', status: 'warning', detail: 'NH-107 cut slope requires rockfall vigilance' },
      { factor: 'Helipad Staging Area', status: 'normal', detail: 'Air rescue staging pad fully dry and operational' }
    ]
  },
  {
    id: 'v-sonprayag',
    name: 'Sonprayag',
    district: 'Rudraprayag',
    riverBasin: 'Mandakini & Vasuki Ganga',
    elevation: 1829,
    population: 1850,
    lat: 30.6303,
    lng: 78.9986,
    riskLevel: 'high',
    floodProbability: 76,
    leadTime: '1 hr 50 mins',
    rainfall1h: 66.5,
    soilMoisture: 86.0,
    waterLevel: 2.90,
    waterLevelTrend: 'rising',
    dischargeRate: 290,
    slopeAngle: 39,
    vulnerableWards: ['Shuttle Terminal', 'Vasuki Ganga Confluence Bank'],
    sensors: ['AWS-RP-05', 'RADAR-RP-05'],
    shelters: ['sh-rudraprayag-pg'],
    whyFactors: [
      { factor: '1h Precipitation Rate', status: 'hazard', detail: '66.5 mm/h intense torrential shower' },
      { factor: 'Topsoil Saturation (TDR)', status: 'hazard', detail: '86.0% saturation - near liquifaction limit on moraine gravels' },
      { factor: 'Dual-Ganga Inflow', status: 'hazard', detail: '2.90 m (+0.55 m in 30 mins from Vasuki Ganga surge)' },
      { factor: 'Pedestrian Chokepoint', status: 'hazard', detail: 'Pilgrim transit corridor flanked by steep colluvial cliffs' },
      { factor: 'Debris Barrier Formation', status: 'warning', detail: 'Narrow pylon clearance threatening hydraulic blockage' }
    ]
  }
];

export const INITIAL_SENSORS = [
  { id: 'AWS-UK-01', name: 'Dharali Upper Met Station', type: 'Automated Rain Gauge', villageId: 'v-dharali', villageName: 'Dharali', value: 18.5, unit: 'mm/h', battery: 96, signal: -68, protocol: 'LoRaWAN 868MHz', status: 'online', lastUpdated: 'Just now' },
  { id: 'SOIL-UK-01', name: 'Dharali Slope TDR Array', type: 'Soil Moisture TDR', villageId: 'v-dharali', villageName: 'Dharali', value: 56.2, unit: '%', battery: 91, signal: -74, protocol: 'LoRaWAN 868MHz', status: 'online', lastUpdated: '2m ago' },
  { id: 'RADAR-UK-01', name: 'Bhagirathi Dharali Bridge Gauge', type: 'Ultrasonic Water Radar', villageId: 'v-dharali', villageName: 'Dharali', value: 1.25, unit: 'm', battery: 88, signal: -62, protocol: '4G LTE / SAT', status: 'online', lastUpdated: '1m ago' },
  { id: 'AWS-CH-01', name: 'Joshimath Sunil Met Node', type: 'Automated Rain Gauge', villageId: 'v-joshimath', villageName: 'Joshimath', value: 68.2, unit: 'mm/h', battery: 84, signal: -81, protocol: '4G LTE', status: 'online', lastUpdated: 'Just now' },
  { id: 'SOIL-CH-01', name: 'Manohar Bagh Moisture Probe', type: 'Soil Moisture TDR', villageId: 'v-joshimath', villageName: 'Joshimath', value: 84.5, unit: '%', battery: 79, signal: -79, protocol: 'LoRaWAN', status: 'online', lastUpdated: '1m ago' },
  { id: 'RADAR-CH-01', name: 'Alaknanda Vishnuprayag Gauge', type: 'Ultrasonic Water Radar', villageId: 'v-joshimath', villageName: 'Joshimath', value: 2.85, unit: 'm', battery: 92, signal: -65, protocol: '4G LTE / SAT', status: 'online', lastUpdated: 'Just now' },
  { id: 'SEISMIC-CH-01', name: 'Dhauliganga Debris Geophone', type: 'Acoustic Geophone', villageId: 'v-joshimath', villageName: 'Joshimath', value: 4.8, unit: 'mm/s', battery: 74, signal: -88, protocol: 'Satellite Iridium', status: 'online', lastUpdated: '3m ago' },
  { id: 'AWS-RP-01', name: 'Kedarnath Temple AWS', type: 'Automated Rain Gauge', villageId: 'v-kedarnath', villageName: 'Kedarnath Valley', value: 42.0, unit: 'mm/h', battery: 95, signal: -72, protocol: 'Satellite VSAT', status: 'online', lastUpdated: 'Just now' },
  { id: 'RADAR-RP-01', name: 'Mandakini Kedar Head Gauge', type: 'Ultrasonic Water Radar', villageId: 'v-kedarnath', villageName: 'Kedarnath Valley', value: 1.85, unit: 'm', battery: 89, signal: -70, protocol: 'Satellite VSAT', status: 'online', lastUpdated: '1m ago' },
  { id: 'AWS-CH-02', name: 'Chamoli DEOC Station', type: 'Automated Rain Gauge', villageId: 'v-chamoli', villageName: 'Chamoli Gopeshwar', value: 36.4, unit: 'mm/h', battery: 98, signal: -55, protocol: 'Fibre / Ethernet', status: 'online', lastUpdated: 'Just now' },
  { id: 'RADAR-CH-02', name: 'Alaknanda Chamoli Bridge', type: 'Ultrasonic Water Radar', villageId: 'v-chamoli', villageName: 'Chamoli Gopeshwar', value: 1.70, unit: 'm', battery: 94, signal: -59, protocol: '4G LTE', status: 'online', lastUpdated: '2m ago' },
  { id: 'AWS-CH-03', name: 'Badrinath Environs AWS', type: 'Automated Rain Gauge', villageId: 'v-badrinath', villageName: 'Badrinath Puri', value: 15.2, unit: 'mm/h', battery: 90, signal: -76, protocol: '4G LTE', status: 'online', lastUpdated: '4m ago' },
  { id: 'RADAR-CH-03', name: 'Badrinath Alaknanda Radar', type: 'Ultrasonic Water Radar', villageId: 'v-badrinath', villageName: 'Badrinath Puri', value: 1.10, unit: 'm', battery: 93, signal: -74, protocol: '4G LTE', status: 'online', lastUpdated: '3m ago' },
  { id: 'AWS-RP-02', name: 'Rudraprayag Sangam AWS', type: 'Automated Rain Gauge', villageId: 'v-rudraprayag', villageName: 'Rudraprayag Sangam', value: 62.0, unit: 'mm/h', battery: 87, signal: -61, protocol: '4G LTE', status: 'online', lastUpdated: 'Just now' },
  { id: 'RADAR-RP-02', name: 'Sangam Confluence Hydro Radar', type: 'Ultrasonic Water Radar', villageId: 'v-rudraprayag', villageName: 'Rudraprayag Sangam', value: 3.10, unit: 'm', battery: 85, signal: -64, protocol: '4G LTE', status: 'online', lastUpdated: 'Just now' },
  { id: 'SOIL-RP-01', name: 'Rudraprayag Escarpment TDR', type: 'Soil Moisture TDR', villageId: 'v-rudraprayag', villageName: 'Rudraprayag Sangam', value: 81.3, unit: '%', battery: 81, signal: -73, protocol: 'LoRaWAN', status: 'online', lastUpdated: '2m ago' },
  { id: 'AWS-UK-02', name: 'Uttarkashi District Met', type: 'Automated Rain Gauge', villageId: 'v-uttarkashi', villageName: 'Uttarkashi', value: 38.0, unit: 'mm/h', battery: 99, signal: -52, protocol: 'Fibre / 4G', status: 'online', lastUpdated: 'Just now' },
  { id: 'RADAR-UK-02', name: 'Bhagirathi Tiloth Radar', type: 'Ultrasonic Water Radar', villageId: 'v-uttarkashi', villageName: 'Uttarkashi', value: 1.95, unit: 'm', battery: 91, signal: -60, protocol: '4G LTE', status: 'online', lastUpdated: '1m ago' },
  { id: 'AWS-PA-01', name: 'Srinagar HNBGU Campus Met', type: 'Automated Rain Gauge', villageId: 'v-srinagar', villageName: 'Srinagar Garhwal', value: 21.0, unit: 'mm/h', battery: 97, signal: -54, protocol: 'Campus LAN', status: 'online', lastUpdated: '3m ago' },
  { id: 'RADAR-PA-01', name: 'Alaknanda Barrage Radar', type: 'Ultrasonic Water Radar', villageId: 'v-srinagar', villageName: 'Srinagar Garhwal', value: 1.40, unit: 'm', battery: 96, signal: -58, protocol: 'Industrial Modbus', status: 'online', lastUpdated: '2m ago' },
  { id: 'AWS-CH-04', name: 'Karnaprayag Upper AWS', type: 'Automated Rain Gauge', villageId: 'v-karnaprayag', villageName: 'Karnaprayag', value: 40.5, unit: 'mm/h', battery: 83, signal: -67, protocol: '4G LTE', status: 'online', lastUpdated: 'Just now' },
  { id: 'RADAR-CH-04', name: 'Pindar-Alaknanda Radar', type: 'Ultrasonic Water Radar', villageId: 'v-karnaprayag', villageName: 'Karnaprayag', value: 2.10, unit: 'm', battery: 86, signal: -69, protocol: '4G LTE', status: 'online', lastUpdated: '1m ago' },
  { id: 'AWS-CH-05', name: 'Mana Frontier Met Post', type: 'Automated Rain Gauge', villageId: 'v-mana', villageName: 'Mana Village', value: 12.0, unit: 'mm/h', battery: 78, signal: -84, protocol: 'Satellite', status: 'online', lastUpdated: '5m ago' },
  { id: 'AWS-RP-03', name: 'Tilwara Mandakini Node', type: 'Automated Rain Gauge', villageId: 'v-tilwara', villageName: 'Tilwara', value: 58.0, unit: 'mm/h', battery: 82, signal: -70, protocol: 'LoRaWAN', status: 'online', lastUpdated: 'Just now' },
  { id: 'RADAR-RP-03', name: 'Tilwara Hydro Gauge', type: 'Ultrasonic Water Radar', villageId: 'v-tilwara', villageName: 'Tilwara', value: 2.70, unit: 'm', battery: 84, signal: -72, protocol: '4G LTE', status: 'online', lastUpdated: 'Just now' },
  { id: 'AWS-CH-06', name: 'Govindghat Riverside AWS', type: 'Automated Rain Gauge', villageId: 'v-govindghat', villageName: 'Govindghat', value: 88.0, unit: 'mm/h', battery: 91, signal: -77, protocol: 'LoRaWAN / SAT', status: 'online', lastUpdated: 'Just now' },
  { id: 'RADAR-CH-06', name: 'Hemganga Flash Radar', type: 'Ultrasonic Water Radar', villageId: 'v-govindghat', villageName: 'Govindghat', value: 3.35, unit: 'm', battery: 89, signal: -75, protocol: '4G LTE', status: 'online', lastUpdated: 'Just now' },
  { id: 'SOIL-CH-02', name: 'Bhyundar Valley TDR Station', type: 'Soil Moisture TDR', villageId: 'v-govindghat', villageName: 'Govindghat', value: 92.5, unit: '%', battery: 85, signal: -82, protocol: 'LoRaWAN', status: 'online', lastUpdated: '1m ago' }
];

export const INITIAL_ALERTS = [
  {
    id: 'ALT-2026-0941',
    villageId: 'v-govindghat',
    villageName: 'Govindghat',
    severity: 'critical',
    title: 'CRITICAL FLASH FLOOD SURGE IMMINENT',
    probability: 92,
    leadTime: '45 mins',
    timestamp: '10 mins ago',
    status: 'active',
    recommendedAction: 'Sound sirens across Sector 2 immediately. Enforce zero-traffic over suspension bridge. Evacuate lower bazaar to Gurudwara Upper Complex.',
    channels: ['Civil Defence Siren', 'SMS Cell Broadcast', 'VHF Radio Ch 4']
  },
  {
    id: 'ALT-2026-0940',
    villageId: 'v-joshimath',
    villageName: 'Joshimath',
    severity: 'high',
    title: 'High Flash Flood & Subsidence Trigger Warning',
    probability: 73,
    leadTime: '2 hrs 15 mins',
    timestamp: '28 mins ago',
    status: 'active',
    recommendedAction: 'Pre-position SDRF rescue boats at Marwari bridge. Activate Community Center shelters. Alert Sunil & Singh Dhar residents of debris danger.',
    channels: ['SMS Cell Broadcast', 'DEOC Hotline']
  },
  {
    id: 'ALT-2026-0938',
    villageId: 'v-rudraprayag',
    villageName: 'Rudraprayag Sangam',
    severity: 'high',
    title: 'Dual-River Confluence Surge Advisory',
    probability: 71,
    leadTime: '2 hrs 40 mins',
    timestamp: '42 mins ago',
    status: 'active',
    recommendedAction: 'Close Sangam Ghat bathing steps to all public. Dispatch police cruisers with PA systems to clear low-lying riverside shops.',
    channels: ['PA Cruiser System', 'Police Wireless']
  },
  {
    id: 'ALT-2026-0935',
    villageId: 'v-tilwara',
    villageName: 'Tilwara',
    severity: 'moderate',
    title: 'Mandakini River Rising Hydro Advisory',
    probability: 48,
    leadTime: '3 hrs 40 mins',
    timestamp: '1 hr ago',
    status: 'acknowledged',
    recommendedAction: 'Monitor Sumerpur flood embankment hourly. Restrict heavy vehicles across the old causeway.',
    channels: ['DEOC Bulletin']
  },
  {
    id: 'ALT-2026-0929',
    villageId: 'v-uttarkashi',
    villageName: 'Uttarkashi',
    severity: 'info',
    title: 'Catchment Rainfall Advisory - Upstream Discharge Elevated',
    probability: 28,
    leadTime: '> 6 hrs',
    timestamp: '2 hrs ago',
    status: 'resolved',
    recommendedAction: 'Standard routine monsoon watch. Maneri Bhali barrage operators notified of upstream rain pulses.',
    channels: ['State Hydrological Bulletin']
  }
];

export const EVACUATION_SHELTERS = [
  { id: 'sh-dharali-gmvn', name: 'GMVN Tourist Rest House Dharali', villageId: 'v-dharali', villageName: 'Dharali', lat: 31.0360, lng: 78.7830, elevation: 2740, capacity: 450, currentOccupancy: 42, roadAccess: 'Paved, High Ground', contact: 'Ramesh Rawat (GMVN In-charge)', phone: '+91-98765-43201', safeRoute: 'Take uphill apple orchard trail away from Kheer Ganga bridge' },
  { id: 'sh-dharali-school', name: 'Government Inter College Upper Dharali', villageId: 'v-dharali', villageName: 'Dharali', lat: 31.0375, lng: 78.7860, elevation: 2780, capacity: 600, currentOccupancy: 0, roadAccess: 'Pedestrian Trail, High ground safe zone', contact: 'Pradeep Joshi (Principal)', phone: '+91-98765-43202', safeRoute: 'Climb 150m via concrete steps behind village temple' },
  { id: 'sh-govindghat-gurudwara-upper', name: 'Gurudwara Sri Hemkund Sahib Upper Complex', villageId: 'v-govindghat', villageName: 'Govindghat', lat: 30.6240, lng: 79.5620, elevation: 1910, capacity: 1200, currentOccupancy: 380, roadAccess: 'Reinforced concrete staging zone', contact: 'S. Harjit Singh (Manager)', phone: '+91-98765-43203', safeRoute: 'Ascend main covered staircase directly behind the langar hall' },
  { id: 'sh-joshimath-inter', name: 'Joshimath Town Hall & Inter College', villageId: 'v-joshimath', villageName: 'Joshimath', lat: 30.5580, lng: 79.5640, elevation: 1940, capacity: 850, currentOccupancy: 120, roadAccess: 'Motorable wide street', contact: 'M. S. Negi (SDM Office)', phone: '+91-98765-43204', safeRoute: 'Follow Ropeway Road uphill, avoid lower bazaar ravine' },
  { id: 'sh-rudraprayag-pg', name: 'Government Post Graduate College Rudraprayag', villageId: 'v-rudraprayag', villageName: 'Rudraprayag Sangam', lat: 30.2880, lng: 78.9850, elevation: 980, capacity: 900, currentOccupancy: 65, roadAccess: 'Highway NH-107 uphill spur', contact: 'Dr. V. K. Bhatt', phone: '+91-98765-43205', safeRoute: 'Head towards Belni bypass ridge away from river ghats' }
];

export const RIVERS_DATA = [
  { name: 'Alaknanda River', basin: 'Alaknanda', flowDir: 'NE to SW', averageDischarge: '420 m3/s', alertThreshold: '2.50 m', dangerLevel: '3.20 m' },
  { name: 'Mandakini River', basin: 'Mandakini', flowDir: 'North to South', averageDischarge: '210 m3/s', alertThreshold: '2.20 m', dangerLevel: '2.90 m' },
  { name: 'Bhagirathi River', basin: 'Bhagirathi', flowDir: 'NE to SW', averageDischarge: '310 m3/s', alertThreshold: '2.00 m', dangerLevel: '2.80 m' },
  { name: 'Dhauliganga River', basin: 'Alaknanda', flowDir: 'East to West', averageDischarge: '180 m3/s', alertThreshold: '2.30 m', dangerLevel: '3.00 m' }
];

export const HISTORICAL_EVENTS = [
  {
    id: 'HIST-2021-02',
    name: '2021 Chamoli Glacial Outburst & Dhauliganga Surge',
    date: 'February 7, 2021',
    affectedBasin: 'Rishi Ganga / Dhauliganga / Alaknanda',
    primaryCause: 'Massive rock/ice avalanche from Ronti Peak triggering glacial lake breach and debris flood',
    peakDischarge: '1,750 m3/s',
    peakRainfall: 'Alpine freeze-thaw with thermal destabilization',
    leadTimeObserved: '14 minutes lead time from Rishi Ganga head to Tapovan barrage',
    casualties: '204 missing/confirmed, 2 hydroelectric plants severely damaged',
    lessonsLearned: 'Hyperlocal acoustic geophones and upstream ultrasonic water radars are mandatory to gain at least 30-45 minutes of critical lead time.'
  },
  {
    id: 'HIST-2023-07',
    name: '2023 Dharali Cloudburst & Kheer Ganga Flash Flood',
    date: 'July 19, 2023',
    affectedBasin: 'Bhagirathi Upper Catchment',
    primaryCause: 'Mesoscale convective cloudburst dropping 118 mm in 65 minutes on saturated moraine slopes',
    peakDischarge: '380 m3/s',
    peakRainfall: '118 mm/h localized cloudburst',
    leadTimeObserved: 'Zero official advance warning issued under traditional radar grid',
    casualties: 'Infrastructure loss, 18 homes damaged, zero fatalities due to daytime vigilance',
    lessonsLearned: 'Hyperlocal soil moisture probes (TDR) would have identified 94% pre-storm saturation 3 hours before cloudburst trigger.'
  },
  {
    id: 'HIST-2013-06',
    name: '2013 Kedarnath Multi-Basin Deluge Benchmark',
    date: 'June 16-17, 2013',
    affectedBasin: 'Mandakini, Alaknanda, Bhagirathi',
    primaryCause: 'Synergy of Western Disturbance with Indian Monsoon and Chorabari Lake moraine collapse',
    peakDischarge: '3,200 m3/s',
    peakRainfall: '375 mm over 24 hours',
    leadTimeObserved: 'Multi-hour latency in downstream emergency dispatch',
    casualties: 'Major regional catastrophe',
    lessonsLearned: 'Decentralized automatic siren telemetry and offline citizen evacuation protocols must operate autonomously without grid power.'
  }
];

export const MODEL_ANALYTICS = {
  modelName: 'HimaGuard Ensemble (XGBoost + Physics-Informed LSTM)',
  labelNote: 'Illustrative Benchmark / Simulated Demonstration Metrics',
  metrics: {
    accuracy: 92.4,
    precision: 89.1,
    recall: 94.2,
    f1Score: 91.6,
    rocAuc: 0.948,
    meanLeadTimeGain: '84 minutes'
  },
  riskDistribution: [
    { name: 'Low Risk', count: 6, color: '#22c55e' },
    { name: 'Moderate Risk', count: 4, color: '#eab308' },
    { name: 'High Risk', count: 3, color: '#f97316' },
    { name: 'Critical Risk', count: 1, color: '#ef4444' }
  ],
  sensorHealth: {
    total: 28,
    online: 28,
    degraded: 0,
    offline: 0,
    uptimePercent: 99.4
  },
  alertStats: {
    totalIssuedPast30Days: 46,
    avgResponseMinutes: 4.2,
    evacuationDrillCompliance: '88%'
  }
};
